name: CI

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: egor-tensin/setup-clang@v1
        with:
          version: 15

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install conan
        run: |
          pip install conan==2.0.4

      - name: Setup conan cache
        uses: actions/cache@v3
        with:
          path: ~/.conan2
          key: ${{ runner.os }}-conan-${{ hashFiles('**/conanfile.txt') }}
          restore-keys: |
            ${{ runner.os }}-conan-

      - name: Install conan CI profile
        run: conan config install .conan

      - name: Lint
        run: make format

      - name: Build
        run: make ci
